---
name: Lint

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Luacheck
        uses: lunarmodules/luacheck@2f764bdcabe8b7c19deadf0e9bb2adc19df1a4c5 # v1.2.0
