---
name: Lint

on: [push, pull_request]

jobs:

  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Luacheck
        uses: lunarmodules/luacheck@f47ad699b5aab8eba5494a2b63e26c24dbf486ce # v1.2.0
