name: "Unix build"

concurrency:
  # for PR's cancel the running task, if another commit is pushed
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  # build on PR and push-to-main. This works for short-lived branches, and saves
  # CPU cycles on duplicated tests.
  # For long-lived branches that diverge, you'll want to run on all pushes, not
  # just on push-to-main.
  pull_request: {}
  push:
    branches:
    - master


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'macos-11.0']
        luaVersion:
        - "5.1"
        - "5.2"
        - "5.3"
        - "5.4"
        - "luajit"
        - "luajit-openresty"
        include:
          - os: "macos-latest"
            luaVersion: "5.4"
          - os: "windows-latest"
            luaVersion: "luajit"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: hishamhm/gh-actions-luarocks@master
        with:
          luarocksVersion: "3.11.0"

      - name: dependencies
        run: |
          luarocks install busted
          luarocks make

      - name: test
        run: |
          busted --Xoutput "--color"

      # - name: Report test coverage
      #   if: success()
      #   continue-on-error: true
      #   run: luacov-coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ github.token }}
